FROM debian
RUN apt-get update -y && apt-get install -y curl
RUN curl -L https://github.com/rmoraes92/http_status_code_check/releases/download/0.1.1/http_status_code_check-x86_64-unknown-linux-gnu > /bin/http_status_code_check && \
    chmod 755 /bin/http_status_code_check

FROM python:3-slim
COPY --from=0 /bin/http_status_code_check /bin/http_status_code_check
CMD ["python", "-m", "http.server"]
