name: Rust

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extra Cargo
      run: cargo install cargo-caw-publish
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --profile release --verbose
#    - name: Publish to crates.io
#      run: cargo caw-publish
    - name: Creating a zip file
      run: zip http_status_code_check.zip target/release/http_status_code_check
    - name: Publish to Github Release
      uses: softprops/action-gh-release@v2
      with:
        files: http_status_code_check.zip

