name: Rust

on:
  push:
    branches: [ "release/*" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# TODO add musl to CI see DEVELOPMENT.md

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extra Cargo
      run: cargo install cargo-caw-publish
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build -r --target x86_64-unknown-linux-gnu
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo caw-publish
    - name: Publish to Github Releases
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # TODO https://github.com/rmoraes92/http_status_code_check/actions/runs/13607277508/job/38040223389
      run: |
        cp target/release/http_status_code_check target/release/http_status_code_check-x86_64-unknown-linux-gnu
        ver=$(cat Cargo.toml | grep -e '^version = ".*"$' | sed 's/version = "\(.*\)"/\1/')
        gh release create --title v$ver --notes-file RELEASE.md $ver target/release/http_status_code_check-x86_64-unknown-linux-gnu
