name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extra Cargo
      run: cargo install cargo-caw-publish
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --profile release
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo caw-publish
    - name: Publish to Github Releases
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ver=$(cat Cargo.toml | grep -e '^version = ".*"$' | sed 's/version = "\(.*\)"/\1/')
        gh release create -d --title v$ver --notes-file RELEASE.md $ver target/release/http_status_code_check
